/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2020-12-14

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include "stm32f0xx.h"

#include "ds18b20.h"
#include "pwm.h"

/* Private macro */
/* Private variables */
/* Private function prototypes */
/* Private functions */

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/
//ds1820, ds18b21

//#define RELAY
#define PID

float temp_ust = 45.0;
float real_temp = 0;

uint32_t temperature = 0;
uint16_t pwm_val = 0;
uint16_t ticks = 100;

//global for possible to change in stm32studio
uint16_t Kp = 0;
float Ki = 0;	//small.... 1.1
uint16_t Kd = 0;

void Init_clock() {
	RCC->CR &= ~RCC_CR_PLLON;
	while(RCC->CR & RCC_CR_PLLRDY);

	RCC->CFGR |= RCC_CFGR_PLLMUL12;

	RCC->CR |= RCC_CR_PLLON;
	while(RCC->CR & RCC_CR_PLLRDY);

	RCC->CFGR |= RCC_CFGR_SW_1;
}

int32_t resP;
int16_t resI;

uint16_t P_set(){
	resP = Kp * (temp_ust - real_temp);

	if (resP < 0) {
		resP = 0;
	}


	return resP;
}

uint16_t I_set(uint8_t reset) {
	static float resI_f = 0;

	resI_f += Ki * (temp_ust - real_temp);

	if (reset == 1) {
		resI_f = 0;
	}

	resI = resI_f;

	if (resI_f < 0) {
		resI = 0;
	}

	return resI;
}

#define REL_START_HEAT()	(GPIOC->BSRR = GPIO_BSRR_BR_6)	//bsrr
#define REL_STOP_HEAT()	(GPIOC->BSRR = GPIO_BSRR_BS_6)

uint8_t cur_rel = 0;
void RelayControl() {
	if (temp_ust < real_temp) {
		REL_STOP_HEAT();
		cur_rel = 0;
		return;
	}
	REL_START_HEAT();
	cur_rel = -1;
}


int main(void)
{
	Init_clock();
	SystemCoreClockUpdate();

#ifdef RELAY
	RCC->AHBENR |= RCC_AHBENR_GPIOCEN;
	GPIOC->MODER |= GPIO_MODER_MODER6_0;
#else if PID
	pwm_init();
	pwm_set_val(1, pwm_val);
#endif

	ds18b20_Init(GPIOC, 13, 12);

  /* TODO - Add your application code here */

  /* Infinite loop */
	while (1)
	{
		ds18b20_StartMeas();
		for (int i = 0; i < 1000; i++) {
			Delay_tick(3400);
		}
//		while(!ds18b20_isConversion());

		temperature = ds18b20_GetTemperature();
		real_temp = (temperature & 0xFFF) * 0.0625;
		real_temp *= (temperature & 0xF000) ? -1 : 1;
#ifdef PID
		pwm_val = P_set() + I_set(0);	//proper
		pwm_set_val(1, pwm_val);
#else if RELAY
		RelayControl();
#endif

		Delay_tick(100);
	}
}
